FROM ubuntu

RUN sudo apt-get update
RUN apt-get install curl -y

RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
RUN sudo apt-get install nodejs -y

# Tools
RUN apt-get install vim -y
RUN sudo apt-get install git -y

CMD /bin/bash
